version: '3'
services:
  arachni:
    build: .
      context: .
      shm_size: '4gb'
    command: bash -c "sleep 10 && entrypoint.sh"
    ports:
      - "7331:7331"
      - "222:22"
      - "9292:9292"
      - "8888-8899:8888-8899"
